### The Spiral Production Configuration Settings
### Settings will be merged into Application Configuration
---

#####################################

smtp:

  ### SMTP server address to connect for service
  host: production.host.domain

#####################################

nicegui:
  ### serve the web service on all networks
  host: '0.0.0.0'
